[package]
name = "amaruensis"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
opencv = "0.94.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
